//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF4
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooKs
    {
        public int ID_BooKs { get; set; }
        public string BooksName { get; set; }
        public int Authors_ID { get; set; }
        public string DateCriation { get; set; }
        public string TypeLit { get; set; }
    
        public virtual Authors Authors { get; set; }
    }
}
